# Generated by Django 6.0.1 on 2026-01-18 08:46

import apps.design_system.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignSystem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the design system",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Name of the design system", max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the design system", verbose_name="Description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Analysis"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the design system analysis",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "design_tokens",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Generated design tokens: colors, typography, spacing, shadows, etc.",
                        null=True,
                        verbose_name="Design Tokens",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking analysis progress",
                        max_length=100,
                        null=True,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "analysis_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if analysis failed",
                        null=True,
                        verbose_name="Analysis Error",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when analysis was completed",
                        null=True,
                        verbose_name="Analyzed At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this design system",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_systems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design System",
                "verbose_name_plural": "Design Systems",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSystemImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original filename of the image",
                        max_length=255,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Uploaded image file (supports local storage or S3)",
                        upload_to=apps.design_system.models.design_system_image_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="image/png", help_text="MIME type of the image", max_length=50, verbose_name="MIME Type"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="File size in bytes", verbose_name="File Size"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image width in pixels", null=True, verbose_name="Width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image height in pixels", null=True, verbose_name="Height"
                    ),
                ),
                (
                    "design_system",
                    models.OneToOneField(
                        help_text="Design system this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="design_system.designsystem",
                        verbose_name="Design System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design System Image",
                "verbose_name_plural": "Design System Images",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="designsystem",
            index=models.Index(fields=["user", "-updated_at"], name="design_syst_user_id_527934_idx"),
        ),
        migrations.AddIndex(
            model_name="designsystem",
            index=models.Index(fields=["status"], name="design_syst_status_0276b2_idx"),
        ),
    ]
