# Generated by Django 6.0.1 on 2026-02-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsystemimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='designsystemimage',
            name='width',
        ),
        migrations.AddField(
            model_name='designsystem',
            name='aesthetic_analysis',
            field=models.TextField(blank=True, default='', help_text='LLM-generated aesthetic analysis in Markdown format: design soul invariants, variation knobs, and anti-patterns', verbose_name='Aesthetic Analysis'),
        ),
    ]
