# Generated by Django 6.0.1 on 2026-01-18 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this API key (e.g., 'Cursor MCP', 'Claude Desktop')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The actual API key value", max_length=64, unique=True, verbose_name="API Key"
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True,
                        help_text="First few characters of the key for identification",
                        max_length=12,
                        verbose_name="Key Prefix",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this API key is currently active", verbose_name="Is Active"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this key was last used",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for the key",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User API Key",
                "verbose_name_plural": "User API Keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="accounts_us_key_a44ec7_idx"),
                    models.Index(fields=["user", "is_active"], name="accounts_us_user_id_57cc3d_idx"),
                ],
            },
        ),
    ]
