# Generated by Django 6.0.1 on 2026-02-26 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userapikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("gemini", "Gemini"), ("openrouter", "OpenRouter")],
                        help_text="LLM provider name",
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(help_text="Fernet-encrypted API key", verbose_name="Encrypted API key"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider configuration is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this LLM configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User LLM configuration",
                "verbose_name_plural": "User LLM configurations",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("user", "provider"), name="unique_user_provider")],
            },
        ),
    ]
