# Generated by Django 6.0.1 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_userllmconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="userllmconfig",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Whether this is the default provider for the user", verbose_name="Is Default"
            ),
        ),
    ]
